baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - tests.py
  - vendor

collections:
  tests:
    output: true

defaults:
  - scope:
      path: ""
      type: tests
    values:
      layout: default
      permalink: /tests/:name
